import type { Block } from '@components/Timer/types'

export const allAboutBTabatas: Block[] = [
  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Buttkickers' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Buttkickers' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Backward Lunges' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 20, label: 'Backwards Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Backward Lunges' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Bell Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Backwards Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Backward Lunges' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Bell Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 2 LB' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Shadow Boxing' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Shadow Boxing' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
    ],
  },
]
