import type { Block } from '@components/Timer/types'

// 14min
export const bringOnTheBurpeesTabatas: Block[] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Double Unders' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Double Unders' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Double Unders' },
    ],
  },
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/4 LB' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Tuck Jump Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Tuck Jump Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Star Jump Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Star Jump Burpees' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
    ],
  },
]
