import type { Props } from '@components/Timer'

// 27min - 1/2 LB x 1 LB
export const cardioCoreCraze: Props['blocks'] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 30, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Sit Throughs' },
      { minutes: 0, seconds: 30, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 30, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Sit Throughs' },
      { minutes: 0, seconds: 30, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Heel Grabber Crunches' },
      { minutes: 0, seconds: 30, label: 'Leg Raises + butt' },
      { minutes: 0, seconds: 45, label: 'Bicycle Crunches' },
      { minutes: 0, seconds: 30, label: 'Flutter Kicks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },

      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Heel Grabber Crunches' },
      { minutes: 0, seconds: 30, label: 'Leg Raises + butt' },
      { minutes: 0, seconds: 45, label: 'Bicycle Crunches' },
      { minutes: 0, seconds: 30, label: 'Flutter Kicks' },
    ],
  },
]
