import type { Block } from '@components/Timer/types'

// 26min - 1/2 LB x 1 LB
export const championsCircuit: Block[] = [
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Jumping Jacks' },
      { minutes: 0, seconds: 30, label: 'Star Jump Burpees' },
      { minutes: 0, seconds: 30, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 30, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 30, label: 'Extended Planks' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Jumping Jacks' },
      { minutes: 0, seconds: 30, label: 'Star Jump Burpees' },
      { minutes: 0, seconds: 30, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 30, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 30, label: 'Extended Planks' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 40, label: 'Swing Kick' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 40, label: 'Swing Kick' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Tuck Jump' },
      { minutes: 0, seconds: 20, label: 'Tuck Jump Burpees' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 20, label: 'Half Burpees' },
      { minutes: 0, seconds: 20, label: 'Surrenders' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 40, label: 'Swing Kick' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 40, label: 'Swing Kick' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Tuck Jump' },
      { minutes: 0, seconds: 20, label: 'Tuck Jump Burpees' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 20, label: 'Half Burpees' },
      { minutes: 0, seconds: 20, label: 'Surrenders' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
    ],
  },
]
