import type { Props } from '@components/Timer'

// 25min - 1/2 LB x 1 LB
export const crazyCardioCircuits: Props['blocks'] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
      { minutes: 0, seconds: 30, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 30, label: 'Half Burpees' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Squat Jumps' },
      { minutes: 0, seconds: 30, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Plank Jacks' },
      { minutes: 0, seconds: 30, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'High Knee Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sprint High Knees' },
      { minutes: 0, seconds: 30, label: 'Speed Skaters' },
      { minutes: 0, seconds: 30, label: 'Standing Cross Knee to Elbow Crunches' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'High Knee Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'Drop Squats' },
      { minutes: 0, seconds: 30, label: 'Surrenders' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'High Knee Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Crab Kicks' },
      { minutes: 0, seconds: 30, label: 'Glute Bridges' },
      { minutes: 0, seconds: 30, label: 'Shin Huggers' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'High Knee Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
    ],
  },
]
