import type { Block } from '@components/Timer/types'

export const everyMinuteCounts: Block[] = [
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Boxer Step - 1 LB' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Right Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Right Side Plank Reach Throughs' },
      { minutes: 0, seconds: 20, label: 'Elbow Planks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Left Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Left Side Plank Reach Throughs' },
      { minutes: 0, seconds: 20, label: 'Elbow Planks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 2 LB' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Crunches' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Glute Bridges' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 15, label: 'Twister Jump' },
      { minutes: 0, seconds: 15, label: 'Boxer Step' },
      { minutes: 0, seconds: 15, label: 'Twister Jump' },
      { minutes: 0, seconds: 15, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'V Ups' },
      { minutes: 0, seconds: 40, label: 'Alternating V Ups' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Flutter Kicks' },
      { minutes: 0, seconds: 40, label: 'Leg Raises' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Twister Jump' },
      { minutes: 0, seconds: 15, label: 'Boxer Step' },
      { minutes: 0, seconds: 15, label: 'Twister Jump' },
      { minutes: 0, seconds: 15, label: 'Boxer Step' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 2 LB' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Sit Throughs' },
      { minutes: 0, seconds: 20, label: 'Extended Planks' },
      { minutes: 0, seconds: 20, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Extended Planks' },
      { minutes: 0, seconds: 20, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
    ],
  },
]
