import type { Block } from '@components/Timer/types'

export const feelTheBurn: Block[] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Alternate Foot - 1/2 LB' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 1, seconds: 0, label: 'Curtsy Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Alternate Foot' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Backward Lunges' },
      { minutes: 0, seconds: 30, label: 'Left Side Lunge Pulse' },
      { minutes: 1, seconds: 0, label: 'Forward Lunge' },
      { minutes: 0, seconds: 30, label: 'Right Side Lunge Pulse' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'High Knee Off Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Squat to Reverse Lunge' },
      { minutes: 0, seconds: 30, label: 'Squat Holds' },
      { minutes: 1, seconds: 0, label: 'Drop Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Holds' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'High Knee Off Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'In Out Squat Hops' },
      { minutes: 1, seconds: 0, label: 'Sumo Squats' },
      { minutes: 0, seconds: 30, label: 'In Out Squat Hops' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 3, seconds: 0, label: 'Freestyle Jump' },
    ],
  },
]
