import type { Block } from '@components/Timer/types'

export const flexFriday: Block[] = [
  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 35, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Push-ups' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Push-ups' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 35, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Push-ups' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Push-ups' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
    ],
  },

  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes - 1 LB' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 35, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Walk-Out Push-ups' },
      { minutes: 0, seconds: 30, label: 'Extended Planks' },
      { minutes: 0, seconds: 30, label: 'Walk-Out Push-ups' },
      { minutes: 0, seconds: 30, label: 'Extended Planks' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 35, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Walk-Out Push-ups' },
      { minutes: 0, seconds: 30, label: 'Extended Planks' },
      { minutes: 0, seconds: 30, label: 'Walk-Out Push-ups' },
      { minutes: 0, seconds: 30, label: 'Extended Planks' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
    ],
  },

  {
    equipment: '2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Hand Release Push-ups' },
      { minutes: 0, seconds: 30, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Hand Release Push-ups' },
      { minutes: 0, seconds: 30, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
    ],
  },
]
