import type { Block } from '@components/Timer/types'

export const fridayFightNight: Block[] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 30, label: 'Basic Jump - 1/2 LB' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Twister Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Scissor Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Right Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Right Side Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Elbow Planks' },
      { minutes: 0, seconds: 20, label: 'Left Side Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Left Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Elbow Planks' },
      { minutes: 0, seconds: 20, label: 'Push-ups' },
      { minutes: 0, seconds: 20, label: 'Extended Planks' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Twister Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Scissor Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Right Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Right Side Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Elbow Planks' },
      { minutes: 0, seconds: 20, label: 'Left Side Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Left Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Elbow Planks' },
      { minutes: 0, seconds: 20, label: 'Push-ups' },
      { minutes: 0, seconds: 20, label: 'Extended Planks' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Twister Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Scissor Jump' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
    ],
  },
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/4 LB' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 20, label: 'Curtsy Squats' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Kicks' },
      { minutes: 0, seconds: 20, label: 'Squat Pulse' },
      { minutes: 0, seconds: 20, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 20, label: 'Curtsy Squats' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Kicks' },
      { minutes: 0, seconds: 20, label: 'Squat Pulse' },
      { minutes: 0, seconds: 20, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
    ],
  },
]
