import type { Props } from '@components/Timer'

// 20min - 1/2 LB
export const goGoCardio: Props['blocks'] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Warrior Crunches' },
      { minutes: 0, seconds: 20, label: 'Sumo Squats' },
      { minutes: 0, seconds: 20, label: 'Narrow to Wide Squat' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Pulse' },
      { minutes: 0, seconds: 20, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 20, label: 'Star Jump Burpees' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Warrior Crunches' },
      { minutes: 0, seconds: 20, label: 'Sumo Squats' },
      { minutes: 0, seconds: 20, label: 'Narrow to Wide Squat' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Pulse' },
      { minutes: 0, seconds: 20, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 20, label: 'Star Jump Burpees' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
    ],
  },
]
