import type { Block } from '@components/Timer/types'

export const harvestHustle: Block[] = [
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 30, label: 'Boxer Step - 1/4 LB' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sumo Squats' },
      { minutes: 0, seconds: 30, label: 'Curtsy Squats' },
      { minutes: 1, seconds: 0, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 30, label: 'Curtsy Squats' },
      { minutes: 0, seconds: 30, label: 'Sumo Squats' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'High Knee Off Step' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'High Knee Off Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sumo Squats' },
      { minutes: 0, seconds: 30, label: 'Curtsy Squats' },
      { minutes: 1, seconds: 0, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 30, label: 'Curtsy Squats' },
      { minutes: 0, seconds: 30, label: 'Sumo Squats' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Cross Feet' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Cross Feet' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Squat Kicks' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Kicks' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Twister Jump' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Twister Jump' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Squat Kicks' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Kicks' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Cross Feet' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Cross Feet' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 30, label: 'Swing Kick' },
    ],
  },
]
