import type { Block } from '@components/Timer/types'

export const heavyRopesAndCoreStrength: Block[] = [
  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'Alternate Foot - 2 LB' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Ski Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Russian Twist' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Ski Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Russian Twist' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Ski Jump' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Scissor Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Elbow Planks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Scissor Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Elbow Planks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Scissor Jump' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 2 LB' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Bicycle Crunches' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Bicycle Crunches' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
    ],
  },
]
