import type { Block } from '@components/Timer/types'

// 24min - 1/2 LB
export const hopItLikeItsHot: Block[] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Drop Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'In Out Squat Hops' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Drop Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'In Out Squat Hops' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Drop Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'In Out Squat Hops' },
      { minutes: 0, seconds: 30, label: 'Squat Pulse' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
    ],
  },
]
