import type { Block } from '@components/Timer/types'

export const hoppingForHeartHealth: Block[] = [
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step - 1/4 LB' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Half Burpees' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Half Burpees' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Tuck Jump' },
      { minutes: 0, seconds: 25, label: 'Tuck Jump Burpees' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Drop Squats' },
      { minutes: 0, seconds: 15, label: 'Squat Jumps' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Tuck Jump' },
      { minutes: 0, seconds: 25, label: 'Tuck Jump Burpees' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Drop Squats' },
      { minutes: 0, seconds: 15, label: 'Squat Jumps' },
    ],
  },
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/4 LB' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Surrenders' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Backward Lunges' },
      { minutes: 0, seconds: 20, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Surrenders' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Backward Lunges' },
      { minutes: 0, seconds: 20, label: 'Lunge Jumps' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 35, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Squat Kicks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Squat Holds' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Squat Kicks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Squat Holds' },
    ],
  },
]
