import type { Block } from '@components/Timer/types'

// 27min - 1/2 LB x 1/4 LB 👍
export const intense: Block[] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'Double Unders' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Double Unders' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Double Unders' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
    ],
  },
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Change Ropes ➡️ 1/4 LB' },
      { minutes: 0, seconds: 45, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Mountain Climbers' },
      { minutes: 0, seconds: 15, label: 'Extended Planks' },
      { minutes: 0, seconds: 15, label: 'Mountain Climbers' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Mountain Climbers' },
      { minutes: 0, seconds: 15, label: 'Extended Planks' },
      { minutes: 0, seconds: 15, label: 'Mountain Climbers' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Alternate Foot' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 35, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Speed Skaters' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Speed Skaters' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Speed Skaters' },
    ],
  },
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Change Ropes ➡️ 1/4 LB' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Squat Jumps' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Squat Jumps' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Lunge Jumps' },
    ],
  },
]
