import type { Block } from '@components/Timer/types'

export const jingleJumpLegBlitz: Block[] = [
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 15, label: 'Basic Jump - 1 LB' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 20, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 2 LB' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Left Side Lunge Pulse' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Right Side Lunge Pulse' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Squat Pulse' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Backward Lunges' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Backward Lunges' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Off Step' },
    ],
  },
]
