import type { Block } from '@components/Timer/types'

export const lilacAndLeaps: Block[] = [
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 30, label: 'Criss-Crosses - 1/4 LB' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 30, label: 'Twister Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Seal Jacks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Twister Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Seal Jacks' },
    ],
  },
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 1/4 LB' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Bell Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Squat Jumps' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Ski Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Squat Jumps' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Bell Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 30, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sprint High Knees' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sprint High Knees' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sprint High Knees' },
    ],
  },
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 1/4 LB' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Seal Jacks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Seal Jacks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Double Unders' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 30, label: 'Mummy Kick Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Mummy Kick Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
    ],
  },
]
