import type { Block } from '@components/Timer/types'

export const muscleUpMonday: Block[] = [
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'Twister Jump - 1 LB' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Push-ups' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Walk-Out Push-ups' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Twister Jump' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Push-ups' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Walk-Out Push-ups' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 2 LB' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Narrow to Wide Squat' },
      { minutes: 0, seconds: 20, label: 'Sumo Squats' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Squat Holds' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Narrow to Wide Squat' },
      { minutes: 0, seconds: 20, label: 'Sumo Squats' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Squat Holds' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 15, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 15, label: 'High Knee Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Leg Raises' },
      { minutes: 0, seconds: 15, label: 'Alternating V Ups' },
      { minutes: 0, seconds: 15, label: 'Bicycle Crunches' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Crunches' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 15, label: 'High Knee Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Leg Raises' },
      { minutes: 0, seconds: 15, label: 'Alternating V Ups' },
      { minutes: 0, seconds: 15, label: 'Bicycle Crunches' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Crunches' },
    ],
  },
]
