import type { Block } from '@components/Timer/types'

export const physEdClass: Block[] = [
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'Basic Jump - 1 LB' },
      { minutes: 0, seconds: 20, label: 'Twister Jump' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Push-ups' },
      { minutes: 0, seconds: 25, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 35, label: 'Elbow Planks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Walk-Out Push-ups' },
    ],
  },

  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
      { minutes: 0, seconds: 15, label: 'Ski Jump' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Glute Bridges' },
      { minutes: 0, seconds: 25, label: 'Glute Bridge Hold' },
      { minutes: 0, seconds: 20, label: 'Glute Bridges' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
      { minutes: 0, seconds: 15, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
      { minutes: 0, seconds: 25, label: 'Squat Holds' },
      { minutes: 0, seconds: 20, label: 'Bodyweight Squats' },
    ],
  },

  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 1 LB' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Right Side Star Plank Hold' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Left Side Star Plank Hold' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Sit Ups' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
    ],
  },

  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 25, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sumo Squats' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Donkey Kick' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sumo Squats' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Alternate Foot' },
    ],
  },

  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Change Ropes - 1 LB' },
      { minutes: 0, seconds: 30, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 15, label: 'Push-ups' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Alternate Foot' },
      { minutes: 0, seconds: 25, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Push-ups' },
      { minutes: 0, seconds: 25, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
    ],
  },

  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 35, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Flutter Kicks' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternating V Ups' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Flutter Kicks' },
    ],
  },
]
