import type { Block } from '@components/Timer/types'

export const planksgivingParty: Block[] = [
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 30, label: 'Elbow Planks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Plank Jacks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Elbow Planks' },
    ],
  },

  {
    equipment: '2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 30, label: 'Extended Planks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Extended Planks' },
    ],
  },

  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes - 1 LB' },
      { minutes: 0, seconds: 30, label: 'Right Side Elbow Plank' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Left Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Right Side Elbow Plank' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Left Side Elbow Plank' },
    ],
  },

  {
    equipment: '2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 30, label: 'Right Side Extended Plank' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Left Side Extended Plank' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Plank Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Right Side Extended Plank' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Left Side Extended Plank' },
    ],
  },
]
