import type { Block } from '@components/Timer/types'

export const pumpUpJumpUpTabatas: Block[] = [
  {
    equipment: 'bodyweight',
    steps: [
      { minutes: 0, seconds: 20, label: 'Push-ups - bodyweight' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Wide Push-ups' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Dive Bomber Push Ups' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Jacks' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Hand Release Push-ups' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Hip Dips' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 20, label: 'Double Unders' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Double Unders' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 2 LB' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Ski Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Basic Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Ski Jump' },
    ],
  },
]
