import type { Block } from '@components/Timer/types'

export const smokingHotHiit: Block[] = [
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 40, label: 'Alternate Foot - 1/4 LB' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Double Unders' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
      { minutes: 0, seconds: 15, label: 'Double Unders' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Squat Jumps' },
      { minutes: 0, seconds: 15, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 15, label: 'Burpees' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Double Unders' },
      { minutes: 0, seconds: 15, label: 'Basic Jump' },
      { minutes: 0, seconds: 15, label: 'Double Unders' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Squat Jumps' },
      { minutes: 0, seconds: 15, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 15, label: 'Burpees' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 30, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'High Knee Jump' },
      { minutes: 0, seconds: 15, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Tuck Jump' },
      { minutes: 0, seconds: 15, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 15, label: 'Tuck Jump Burpees' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'High Knee Jump' },
      { minutes: 0, seconds: 15, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Tuck Jump' },
      { minutes: 0, seconds: 15, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 15, label: 'Tuck Jump Burpees' },
    ],
  },
]
