import type { Props } from '@components/Timer'

// 28min - 1/2 LB x 1 LB
export const summerGlowGrinder: Props['blocks'] = [
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Swing Kick' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sprint High Knees' },
      { minutes: 0, seconds: 20, label: 'Squat Holds' },
      { minutes: 0, seconds: 30, label: 'Speed Skaters' },
      { minutes: 0, seconds: 20, label: 'Squat Holds' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Holds' },
      { minutes: 0, seconds: 30, label: 'Standing Cross Knee to Elbow Crunches' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 1, seconds: 0, label: 'Swing Kick' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sprint High Knees' },
      { minutes: 0, seconds: 20, label: 'Squat Holds' },
      { minutes: 0, seconds: 30, label: 'Speed Skaters' },
      { minutes: 0, seconds: 20, label: 'Squat Holds' },
      { minutes: 0, seconds: 30, label: 'Ratchet Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Holds' },
      { minutes: 0, seconds: 30, label: 'Standing Cross Knee to Elbow Crunches' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 20, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Half Burpees' },
      { minutes: 0, seconds: 20, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Plank Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Sit Throughs' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 1, seconds: 0, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 20, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Half Burpees' },
      { minutes: 0, seconds: 20, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Plank Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Bear Hold' },
      { minutes: 0, seconds: 30, label: 'Sit Throughs' },
    ],
  },
]
