import type { Block } from '@components/Timer/types'

export const sunshineStrength: Block[] = [
  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 40, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Donkey Kick' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Donkey Kick' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Freestyle Jump' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 1 LB' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 20, label: 'Extended Planks' },
      { minutes: 0, seconds: 20, label: 'Plank Shoulder Taps' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Extended Planks' },
      { minutes: 0, seconds: 20, label: 'Plank Up Downs' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 25, label: 'Basic Jump' },
      { minutes: 0, seconds: 25, label: 'Ski Jump' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Squat Jumps' },
      { minutes: 0, seconds: 30, label: 'Squat Holds' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Basic Jump' },
      { minutes: 0, seconds: 25, label: 'Ski Jump' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Squat Kicks' },
      { minutes: 0, seconds: 30, label: 'Squat Holds' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Basic Jump' },
      { minutes: 0, seconds: 25, label: 'Ski Jump' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 1 LB' },
      { minutes: 0, seconds: 30, label: 'Scissor Jump' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Glute Bridges' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Scissor Jump' },
      { minutes: 0, seconds: 30, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Glute Bridge Hold' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Freestyle Jump' },
    ],
  },

  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 35, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Right Side Elbow Plank' },
      { minutes: 0, seconds: 15, label: 'Right Side Hip Dips' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Left Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Left Side Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Right Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Right Side Hip Dips' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Left Side Elbow Plank' },
      { minutes: 0, seconds: 20, label: 'Left Side Hip Dips' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Freestyle Jump' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 1 LB' },
      { minutes: 0, seconds: 40, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Forward Lunge' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Backward Lunges' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 50, label: 'Freestyle Jump' },
    ],
  },

  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 2 LB' },
      { minutes: 0, seconds: 35, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternating V Ups' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Freestyle Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'V Ups' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternating V Ups' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Basic Jump' },
    ],
  },

  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes - 1 LB' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Dive Bomber Push Ups' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Walk-Out Push-ups' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Wide Push-ups' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Boxer Step' },
    ],
  },
]
