import type { Block } from '@components/Timer/types'

// 29min - 1/2 LB x 1/4 LB
export const weeksEndHiit: Block[] = [
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 1, seconds: 0, label: 'Boxer Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 1, seconds: 0, label: 'Jumping Jacks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Speed Skaters' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Cross-Mountain Climbers' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Double Unders' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Tuck Jump' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 45, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 45, label: 'Jump Rope Off Step' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 45, label: 'Seal Jacks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Drop Squats' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Criss-Crosses' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 35, label: 'Shadow Boxing' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'High Knee Jump' },
      { minutes: 0, seconds: 10, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Sprint High Knees' },
    ],
  },
  {
    equipment: '1/4 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 1/4 LB' },
      { minutes: 0, seconds: 40, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Scissor Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Mountain Climbers' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Mountain Climbers' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
    ],
  },
  {
    equipment: '1/2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 1/2 LB' },
      { minutes: 0, seconds: 40, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Jump Rope Jacks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Lunge Jumps' },
    ],
  },
]
