import type { Props } from '@components/Timer'

// 20min - 1 LB x 2 LB
export const winningWednesday: Props['blocks'] = [
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Squat Jumps' },
      { minutes: 0, seconds: 30, label: 'Burpees' },
      { minutes: 0, seconds: 40, label: 'Extended Planks' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'High Knee Jump' },
      { minutes: 0, seconds: 25, label: 'Alternate Foot' },
      { minutes: 0, seconds: 10, label: 'High Knee Jump' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 15, label: 'Squat Jumps' },
      { minutes: 0, seconds: 25, label: 'Burpees' },
      { minutes: 0, seconds: 35, label: 'Extended Planks' },
      { minutes: 0, seconds: 20, label: 'Rest' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'High Knee Jump' },
    ],
  },
  {
    equipment: '2 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 2 LB' },
      { minutes: 0, seconds: 25, label: 'Boxer Step' },
      { minutes: 0, seconds: 15, label: 'Alternate Foot' },
      { minutes: 0, seconds: 25, label: 'Boxer Step' },
      { minutes: 0, seconds: 15, label: 'Alternate Foot' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 40, label: 'Drop Squats' },
      { minutes: 0, seconds: 30, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 20, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 30, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Alternate Foot' },
      { minutes: 0, seconds: 20, label: 'Boxer Step' },
      { minutes: 0, seconds: 10, label: 'Alternate Foot' },
      { minutes: 0, seconds: 25, label: 'Rest' },

      { minutes: 0, seconds: 30, label: 'Drop Squats' },
      { minutes: 0, seconds: 20, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 10, label: 'Lunge Jumps' },
      { minutes: 0, seconds: 25, label: 'Rest' },
      { minutes: 0, seconds: 25, label: 'Boxer Step' },
      { minutes: 0, seconds: 15, label: 'Alternate Foot' },
    ],
  },
  {
    equipment: '1 LB',
    steps: [
      { minutes: 0, seconds: 50, label: 'Change Ropes ➡️ 1 LB' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'Burpees' },
      { minutes: 0, seconds: 30, label: 'Squat Thrusts' },
      { minutes: 0, seconds: 15, label: 'Rest' },
      { minutes: 0, seconds: 20, label: 'High Knee Jump' },
      { minutes: 0, seconds: 30, label: 'Alternate Foot' },
    ],
  },
]
